pipelines:
  - name: pipeline_affinityGroup_example2
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_1
        type: Bash
        execution:
          onExecute:
            - echo "Running " $pipeline_name
      - name: bad
        type: Bash
        execution:
          onExecute:
            - echo "Running " $pipeline_name
      - name: ag_step_3
        type: Bash
        execution:
          onExecute:
            - echo "Running " $pipeline_name