pipelines:
  - name: pipeline_affinityGroup_example
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
          affinityGroup: together
        execution:
          onExecute:
            - mkdir $MY_DIR
            - echo "Running " $pipeline_name "|"
      - name: bad
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
            - name: ag_step_1
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|"
      - name: ag_step_3
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
            - name: bad
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|"