pipelines:
  - name: pipeline_affinityGroup_example
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
        execution:
          onExecute:
            - mkdir $MY_DIR
            - echo "Running " $pipeline_name "|" $step_name >$MY_DIR/myoutput.txt
            - cat $MY_DIR/myoutput.txt
      - name: bad
        type: Bash
        configuration:
          inputSteps:
            - name: ag_step_1
        execution:
          onExecute:
            - cat $MY_DIR/myoutput.txt
      - name: ag_step_3
        type: Bash
        configuration:
          inputSteps:
            - name: bad
        execution:
          onExecute:
            - cat $MY_DIR/myoutput.txt