pipelines:
  - name: pipeline_affinityGroup_example4
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_1
        type: Bash
        execution:
          onExecute:
            - mkdir $MY_DIR
            - echo "Running " $pipeline_name "|" $step_name >$MY_DIR/myoutput.txt
            - cat $MY_DIR/myoutput.txt
            - touch cachefile.txt
            - add_pipeline_files cachefile.txt my_file
      - name: bad
        type: Bash
        configuration:
          inputSteps:
            - name: ag_step_1
        execution:
          onStart:
            - restore_pipeline_files my_file cachefile.txt
          onExecute:
            - echo "Hello world4"
            - cat $MY_DIR/myoutput.txt