pipelines:
  - name: pipeline_affinityGroup_example1
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_1
        type: Bash
        execution:
          onExecute:
            - mkdir $MY_DIR
            - echo "Running " $pipeline_name "|" $step_name >$MY_DIR/myoutput.txt
            - cat $MY_DIR/myoutput.txt
            - touch foo
            - add_pipeline_files foo foo
      - name: bad
        type: Bash
        configuration:
          inputSteps:
            - name: ag_step_1
        execution:
          onStart:
            - restore_pipeline_files foo
          onExecute:
            - echo "Hello world"
            - cat $MY_DIR/myoutput.txt