pipelines:
  - name: pipeline_affinityGroup_example7
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_{{$i}}
        type: Bash
        execution:
          onExecute:
            - mkdir $MY_DIR
            - echo "Running " $pipeline_name "|" $step_name >$MY_DIR/myoutput.txt
            - cat $MY_DIR/myoutput.txt
            - echo "new daniel" > cachefile.txt
            - add_pipeline_files cachefile.txt my_file